dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: emailService_provider #应用名称
  registry:
    address: zookeeper://192.168.231.1   #注册中心的ip可以直接加上端口，也可以同下面的port设置
    timeout: 6000   #超时时间设置，太短可能会报错单位是  ms也就是6秒
    port: 2181
    check: false
  metadata-report:
    address: zookeeper://192.168.231.1:2181
  protocol:     #指定使用dubbo协议，端口是20880可以是其他端口不影响使用
    name: dubbo
    port: 20881
  scan: #扫描包路径下面的服务
    base-packages: com.shu.mp.email.dubbo.service  #服务暴露与发现消费所在的package
  monitor:
    protocol: registry




spring:
  datasource:
    username: root
    password: 124823
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=UTC

  jpa:
    # 在建表的时候，将默认的存储引擎切换为 InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 配置在日志中打印出执行的 SQL 语句信息。
    show-sql: true
    # 配置指明在程序启动的时候要删除并且创建实体类对应的表。
    hibernate:
      ddl-auto: update #create
